// Sample articles for the inner-page template.
// Each article is a list of typed content blocks. Add new articles
// here by giving them a slug key. Block types supported:
//   h2 · h3 · paragraph · image · table · list · callout · kpis
//   two-col · steps · faq · cta · divider

window.Articles = {

  // ── 1 · DATA-HEAVY · 大量表格、少圖 ──────────────────────────────
  'asia-miles': {
    meta: {
      breadcrumb: ['主頁', '攻略', 'Asia Miles'],
      tags: [
        { label: 'ASIA MILES', tone: 'black' },
        { label: '攻略', tone: 'gray' },
      ],
      title: 'Asia Miles 2026年5月國泰飛行里數兌換表',
      lede: '國泰宣佈由 5 月 1 日起調整 Asia Miles 兌換表，**長途加 3.48%、短途減 10%**，日本航線維持不變。本文用一張表帶你睇清所有變動及應對策略。',
      author: '里數情報組',
      authorRole: '編輯',
      date: '2026年5月23日',
      updated: '2026年5月23日 14:30',
      readTime: '8 分鐘',
      hero: null,
    },
    blocks: [
      { type: 'kpis', label: 'TL;DR · 重點摘要',
        items: [
          { label: '生效日', value: '2026年5月1日' },
          { label: '長途航線', value: '最高 +3.48%', tone: 'up' },
          { label: '短途航線', value: '最高 −10.00%', tone: 'down' },
          { label: '日本航線', value: '維持不變', tone: 'flat' },
        ],
        bullets: [
          '新表 2026 年 5 月 1 日（香港時間）凌晨生效，已換票記錄不受影響。',
          '商務艙係今次調整重災區 — 長途航線最多多付 4,000 里。',
          '短途商務艙係贏家 — 北京、上海、首爾、曼谷少付 1,000 里。',
        ],
      },
      { type: 'h2', text: '新里數兌換表（2026 年 5 月 1 日起）',
        sub: '括弧內為單程所需里數，▲ 代表加幅、▼ 代表減幅，灰色為持平。' },
      { type: 'table',
        headers: ['距離區域 · 例子', '經濟', '豪華經濟', '商務', '頭等'],
        align: ['left', 'right', 'right', 'right', 'right'],
        rows: [
          ['超短途\n1–750 哩\n台北、河內、馬尼拉', '7,000', '11,000', '16,000', '—'],
          ['短途 Ⅰ\n751–2,750 哩\n北京、上海、首爾、曼谷', '9,000', { value: '18,000', delta: -10.00 }, { value: '27,000', delta: -3.57 }, '43,000'],
          ['短途 Ⅱ\n751–2,750 哩\n普吉、檳城、吉隆坡、新加坡', '13,000', '23,000', '32,000', '50,000'],
          ['中途\n2,751–5,000 哩\n東京、大阪、札幌、福岡', { value: '20,000', badge: '日本維持' }, '38,000', { value: '60,000', delta: 3.45 }, '90,000'],
          ['長途\n5,001–7,500 哩\n悉尼、墨爾本、溫哥華', '27,000', '50,000', { value: '91,000', delta: 3.41 }, '125,000'],
          ['超長途\n7,501+ 哩\n倫敦、紐約、波士頓', '38,000', '75,000', { value: '119,000', delta: 3.48 }, '160,000'],
        ],
        footnotes: ['數據來源：國泰航空 2026 年 4 月公告', '不含稅項及燃油附加費', '同行夥伴票同步調整'],
      },
      { type: 'h2', text: '贏家 vs 輸家',
        sub: '以全年慣常旅客（每月 2 程）計算，假設一半短途、一半長途。' },
      { type: 'two-col',
        left:  { title: '受惠 · WINNERS', tone: 'good', items: [
          '短途商務客（北京、上海、首爾、曼谷）省 1,000 里',
          '經濟艙短途客所有區域里數不變',
          '頻飛日本旅客 — 完全唔受影響',
          '會員 Gold/Diamond 級數兌換折扣維持',
        ]},
        right: { title: '受影響 · LOSERS', tone: 'bad', items: [
          '長途商務客（悉尼、墨爾本）每程多付 3,000 里',
          '超長途商務客（倫敦、紐約）每程多付 4,000 里',
          '中途商務客（東京除外）受 +3.45% 影響',
          '同行夥伴票價同步上調',
        ]},
      },
      { type: 'h2', text: '新表生效後點換票？5 步走' },
      { type: 'steps', items: [
        { title: '登入 Cathay App', desc: '使用會員號或電郵登入，確認里數結餘。' },
        { title: '搜尋換票航班', desc: '選擇「以里數兌換」，輸入出發地、目的地、日期。' },
        { title: '揀座位艙等', desc: '參考新表，比較經濟／豪經／商務里數差。' },
        { title: '確認旅客資料', desc: '可為自己或已登記同行家人換票。' },
        { title: '完成扣里數', desc: '扣除指定里數及繳付稅項燃油費。' },
      ]},
      { type: 'h2', text: '常見問題' },
      { type: 'faq', items: [
        { q: '新表幾時生效？', a: '由 2026年5月1日（香港時間）凌晨零時起，所有新訂位均按新表扣除里數。' },
        { q: '5月1日前已換到嘅票會唔會被追收？', a: '不會。已確認嘅換票記錄按原有里數計算，不會追收差額。' },
        { q: '日本航線真係完全唔變？', a: '經濟艙、豪華經濟、頭等維持不變；中途商務艙整體 +3.45%，但東京、大阪等熱門點仍享舊價。' },
        { q: '可唔可以混合艙等換票？', a: '可以，國泰系統會分段計算各程所需里數，按航段加總。' },
      ]},
      { type: 'cta' },
    ],
    related: [
      { cat: 'AE', title: '美國運通優先購票！US Open 2026 買一送一', tag: '剩 5 天', tone: 'navy' },
      { cat: 'ASIA MILES', title: '20% Bonus！Asia Miles 轉 Marriott Bonvoy', tag: '剩 19 天', tone: 'dark' },
      { cat: 'AEON', title: 'AEON 信用卡 AEON Stores 高達 10% 簽賬賞', tag: '長期', tone: 'blue' },
    ],
  },

  // ── 2 · IMAGE-HEAVY · 信用卡優惠長文 ────────────────────────────
  'aeon-stores': {
    meta: {
      breadcrumb: ['主頁', '優惠情報', '信用卡'],
      tags: [
        { label: 'AEON', tone: 'black' },
        { label: '優惠情報', tone: 'gray' },
      ],
      title: 'AEON 信用卡 AEON Stores 簽賬高達 10% 回贈',
      lede: '配合 AEON Stores 35 週年，AEON 信用卡客戶於指定分店簽賬可享 **高達 10% 簽賬回贈**，並支援 Apple Pay、Google Pay 自動參加。',
      author: '優惠情報組',
      authorRole: '記者',
      date: '2026年5月20日',
      updated: '2026年5月23日 09:10',
      readTime: '4 分鐘',
      hero: { label: 'AEON Stores · 主視覺', ratio: '21/9', tint: 'gold' },
    },
    blocks: [
      { type: 'kpis', label: '優惠速覽',
        items: [
          { label: '回贈率', value: '高達 10%', tone: 'good' },
          { label: '優惠期', value: '即日至 5月31日' },
          { label: '指定分店', value: '全線 AEON Stores' },
          { label: '最低簽賬', value: '無門檻' },
        ],
      },
      { type: 'paragraph', text: 'AEON 信用卡今年慶祝 AEON Stores 進駐香港 35 週年，推出長達一個月嘅高達 10% 簽賬回贈活動。優惠覆蓋全線 AEON Stores 分店，包括康怡、太古城、樂富等，亦適用於 AEON Style 自家品牌貨品。' },
      { type: 'image', caption: 'AEON 信用卡 × Apple Pay 自動參加，無需登記。', ratio: '16/9', tint: 'blue' },
      { type: 'h2', text: '回贈分級點計？' },
      { type: 'paragraph', text: '回贈率按每月累計簽賬金額分三級計算。每月由 1 號重新累計，回贈會於下個月 25 號自動入賬到客戶嘅信用卡賬戶。' },
      { type: 'table',
        headers: ['每月累計簽賬', '回贈率', '每月回贈上限'],
        align: ['left', 'right', 'right'],
        rows: [
          ['HK$ 0 – 1,999', '3%', 'HK$ 60'],
          ['HK$ 2,000 – 4,999', '6%', 'HK$ 300'],
          ['HK$ 5,000 或以上', { value: '10%', badge: '最高' }, 'HK$ 1,000'],
        ],
        footnotes: ['每月最高總回贈為 HK$ 1,000 / 卡戶', '回贈將於下個月 25 號自動入賬'],
      },
      { type: 'h2', text: '邊啲簽賬可以攞回贈？' },
      { type: 'list', kind: 'ul', items: [
        '✓ 全線 AEON Stores 實體店簽賬（包括 AEON Style、AEON Daily）',
        '✓ AEON Online Shop 網購（除特定品牌）',
        '✓ Apple Pay、Google Pay、八達通 AEON 信用卡感應簽賬',
        '✗ 不適用於儲值卡增值、繳費、保險、賬單分期',
        '✗ 不適用於非 AEON 自家品牌商戶嘅租戶分店',
      ]},
      { type: 'image', caption: 'AEON Style 自家品牌貨品同樣參加。', ratio: '16/9', tint: 'pink' },
      { type: 'h2', text: '配對其他優惠仲有幾多回贈？' },
      { type: 'paragraph', text: '今次活動可同時疊加 AEON 信用卡基本回贈率（0.4%）及指定銀行優惠。配合 Mastercard 海外網購 1.5% 額外回贈，總回贈率可達 **11.9%**。' },
      { type: 'two-col',
        left:  { title: '建議組合', tone: 'good', items: [
          '配 Apple Pay：自動參加，無需登記',
          '搭夠 HK$5,000 達到最高 10%',
          '配合 AEON Members Day 再多 5% 折扣',
          '每月 1 號重新計算，可分批簽賬',
        ]},
        right: { title: '常見伏位', tone: 'bad', items: [
          '繳費、保險、儲值卡增值唔計簽賬',
          '上月退貨會喺下月扣返回贈',
          '網購要選 AEON Online Shop 先有效',
          '租戶分店（如書店、餐廳）唔計入',
        ]},
      },
      { type: 'callout', tone: 'info', text: '記得確認你嘅 AEON 信用卡已開通 Apple Pay 或 Google Pay，部分舊版實體卡需要先在 App 內升級至 EMV 版本先支援感應簽賬。' },
      { type: 'cta' },
    ],
    related: [
      { cat: '恒生', title: '恒生 MMPOWER World Mastercard 2026 升級版', tag: '長期', tone: 'red' },
      { cat: 'ASIA MILES', title: '5月 App 賞里啟航 — 預訂愈多里數愈多', tag: '剩 8 天', tone: 'navy' },
      { cat: 'AEON', title: 'AEON 信用卡迎新：HK$700 現金回贈', tag: '長期', tone: 'gold' },
    ],
  },

  // ── 3 · MIXED · 評測型 ────────────────────────────────────────
  'hangseng-mmpower': {
    meta: {
      breadcrumb: ['主頁', '攻略', '信用卡'],
      tags: [
        { label: '恒生', tone: 'black' },
        { label: '評測', tone: 'gray' },
      ],
      title: '恒生 MMPOWER World Mastercard 2026 升級版值唔值得申請？',
      lede: '恒生今年將 MMPOWER 升級為 World Mastercard 級，迎新 HK$1,200 現金回贈，**指定戶口及網購 8% 回贈**。我哋實試三個月，告訴你最大伏位在邊。',
      author: '阿 Ken',
      authorRole: '特約評測',
      date: '2026年5月18日',
      updated: '2026年5月23日',
      readTime: '6 分鐘',
      hero: { label: '恒生 MMPOWER · 卡面設計', ratio: '21/9', tint: 'red' },
    },
    blocks: [
      { type: 'callout', tone: 'verdict', label: '我哋嘅評分',
        text: '**4.2 / 5 ★** · 適合恒生主戶口客戶，網購 + 海外消費比例高嘅人最值。但唔係恒生客就要諗清楚。' },
      { type: 'paragraph', text: '恒生 MMPOWER 第一代喺 2022 年推出時，定位係「年輕人入門信用卡」，主打 2% 現金回贈無上限。今年呢張卡升級成 World Mastercard 級，迎新 HK$1,200 加碼，仲多咗指定類別 8% 回贈。' },
      { type: 'image', caption: '新版卡面採用啞光磨砂工藝，比舊版質感升級。', ratio: '16/9', tint: 'red' },
      { type: 'h2', text: '三大升級重點' },
      { type: 'list', kind: 'ol', items: [
        '**回贈率提升** — 指定類別由 2% 增至 8%，包括網購、串流訂閱、本地交通。',
        '**迎新加碼** — 首三個月簽滿 HK$8,000 送 HK$1,200 現金回贈，回贈率高達 15%。',
        '**World Mastercard 禮遇** — 全球機場貴賓室每年 2 次免費使用，旅遊保險升級。',
      ]},
      { type: 'image', caption: 'App 內可即時睇返每月回贈累計。', ratio: '16/9', tint: 'blue' },
      { type: 'h2', text: '邊啲簽賬有 8% 回贈？',
        sub: '官方列出 6 個指定類別，但實測有部分商戶唔算入。' },
      { type: 'table',
        headers: ['類別', '官方寫法', '實測'],
        align: ['left', 'left', 'left'],
        rows: [
          ['網購', '所有香港網購商戶', { value: '✓ 大部分得', badge: '有效' }],
          ['串流', 'Netflix、Spotify、Disney+', { value: '✓ 自動計', badge: '有效' }],
          ['交通', '港鐵、巴士、的士', { value: '✓ 八達通自動增值同計', badge: '有效' }],
          ['食肆', '指定餐廳', '△ 只計指定品牌，連鎖店冇份'],
          ['超市', 'Wellcome、PARKnSHOP', '✗ 唔計入網購'],
          ['海外', '所有海外簽賬', { value: '✓ 連手續費都計', badge: '有效' }],
        ],
      },
      { type: 'callout', tone: 'warn', label: '注意',
        text: '8% 回贈每月上限 HK$400（即每月最多 HK$5,000 簽賬攞到最高回贈）。超出上限嘅部分按基本 0.4% 計，係 20 倍差距，記得分卡用。' },
      { type: 'h2', text: '邊啲人最值得申請？' },
      { type: 'two-col',
        left:  { title: '推薦申請', tone: 'good', items: [
          '已經係恒生客戶（有 Personal Integrated A/C）',
          '每月網購 + 海外消費 HK$5,000 以上',
          '經常用 Netflix、Spotify、Disney+',
          '需要機場貴賓室但唔想畀年費',
        ]},
        right: { title: '可能唔啱', tone: 'bad', items: [
          '主要簽賬係超市、食肆嘅人',
          '已有 DBS Black Card 或 Citi Prestige',
          '極少網購、極少出 trip',
          '月簽賬少於 HK$2,000',
        ]},
      },
      { type: 'h2', text: '迎新點先攞到 HK$1,200？' },
      { type: 'steps', items: [
        { title: '新客 / 升級客均合資格', desc: '由舊版 MMPOWER 升級至 World Mastercard 都當新客，可攞迎新。' },
        { title: '首 60 日內登記', desc: '收到實體卡後，喺 Hang Seng Personal e-Banking 內登記參加。' },
        { title: '首 3 個月簽夠 HK$8,000', desc: '本地、海外、網購都計，最低 HK$30 / 筆。' },
        { title: '第 4 個月入賬', desc: 'HK$1,200 現金回贈會直接扣返出年費 / 賬單結餘。' },
      ]},
      { type: 'callout', tone: 'info', text: '想知自己每月會儲到幾多回贈？打開 HK Miles App 嘅「我的卡」功能，輸入每月平均簽賬，App 會即時算出最佳卡組合。' },
      { type: 'cta' },
    ],
    related: [
      { cat: 'CITI', title: 'Citi PremierMiles 2026 新增 8% 海外網購', tag: '剩 30 天', tone: 'blue' },
      { cat: 'DBS', title: 'DBS Black World Mastercard 評測', tag: '長期', tone: 'dark' },
      { cat: 'AE', title: 'American Express Cathay Elite 卡：值唔值申請？', tag: '長期', tone: 'navy' },
    ],
  },

};
